load File.expand_path('tasks/helpers.rake',  __dir__)
load File.expand_path('tasks/config.rake',   __dir__)
load File.expand_path('tasks/logs.rake',     __dir__)
load File.expand_path('tasks/sh.rake',       __dir__)
load File.expand_path('tasks/systemd.rake',  __dir__)
load File.expand_path('tasks/transfer.rake', __dir__)
